version: "3.8"
services:
  confusion-server:
    build: .
    ports: 
      - "3443:3443"
      - "3000:3000"
    container_name: confusion-server
    depends_on: 
      - mongo
  mongo:
    image : mongo:latest
    container_name: mongo
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
       - ./database:/data/db
    ports:
      - 27017:27017



  